export const testAllWeeklyData = {
    "calorieData": [
        {
            "date": "2024-10-23",
            "steps": 501
        },
        {
            "date": "2024-10-24",
            "steps": 1129
        },
        {
            "date": "2024-10-25",
            "steps": 1141
        },
        {
            "date": "2024-10-27",
            "steps": 375
        },
        {
            "date": "2024-10-28",
            "steps": 1082
        }
    ],
    "totalCaloriesWeekly": 4228,
    "heartRateAvgData": [
        {
            "date": "2024-10-23",
            "avgHr": 129
        },
        {
            "date": "2024-10-24",
            "avgHr": 145
        },
        {
            "date": "2024-10-25",
            "avgHr": 134
        },
        {
            "date": "2024-10-27",
            "avgHr": 103
        },
        {
            "date": "2024-10-28",
            "avgHr": 160.7
        }
    ],
    "heartRateAvg": 133,
    "weeklyRunningMiles": 22978.5,
    "totalWeeklyHours": 27543,
    "weeklyWorkoutTimes": [
        {
            "day": "1",
            "time": 51
        },
        {
            "day": "2",
            "time": 14
        },
        {
            "day": "3",
            "time": 28
        },
        {
            "day": "4",
            "time": 87
        },
        {
            "day": "5",
            "time": 22
        },
        {
            "day": "6",
            "time": 60
        },
        {
            "day": "7",
            "time": 49
        },
        {
            "day": "8",
            "time": 67
        },
        {
            "day": "9",
            "time": 77
        }
    ],
    "weeklySufferScore": null,
    "weeklyHeartRateMaxes": [
        {
            "date": "2024-10-23",
            "time": 148
        },
        {
            "date": "2024-10-23",
            "time": 167
        },
        {
            "date": "2024-10-24",
            "time": 185
        },
        {
            "date": "2024-10-24",
            "time": 163
        },
        {
            "date": "2024-10-25",
            "time": 176
        },
        {
            "date": "2024-10-25",
            "time": 124
        },
        {
            "date": "2024-10-25",
            "time": 163
        },
        {
            "date": "2024-10-27",
            "time": 142
        },
        {
            "date": "2024-10-28",
            "time": 177
        }
    ]
}
export const testAthleteStatsData = {
    "totalRunQty": 13,
    "totalRunDistance": 37399,
    "totalRunTime": 15769
}
export const testAllData = {
    "calorieData": [
        {
            "date": "2024-10-23",
            "steps": 501
        },
        {
            "date": "2024-10-24",
            "steps": 1129
        },
        {
            "date": "2024-10-25",
            "steps": 1141
        },
        {
            "date": "2024-10-27",
            "steps": 375
        },
        {
            "date": "2024-10-28",
            "steps": 1082
        }
    ],
    "totalCaloriesWeekly": 4228,
    "heartRateAvgData": [
        {
            "date": "2024-10-23",
            "avgHr": 129
        },
        {
            "date": "2024-10-24",
            "avgHr": 145
        },
        {
            "date": "2024-10-25",
            "avgHr": 134
        },
        {
            "date": "2024-10-27",
            "avgHr": 103
        },
        {
            "date": "2024-10-28",
            "avgHr": 160.7
        }
    ],
    "heartRateAvg": 133,
    "weeklyRunningMiles": 22978.5,
    "totalWeeklyHours": 27543,
    "weeklyWorkoutTimes": [
        {
            "day": "1",
            "time": 51
        },
        {
            "day": "2",
            "time": 14
        },
        {
            "day": "3",
            "time": 28
        },
        {
            "day": "4",
            "time": 87
        },
        {
            "day": "5",
            "time": 22
        },
        {
            "day": "6",
            "time": 60
        },
        {
            "day": "7",
            "time": 49
        },
        {
            "day": "8",
            "time": 67
        },
        {
            "day": "9",
            "time": 77
        }
    ],
    "weeklySufferScore": null,
    "weeklyHeartRateMaxes": [
        {
            "date": "2024-10-23",
            "time": 148
        },
        {
            "date": "2024-10-23",
            "time": 167
        },
        {
            "date": "2024-10-24",
            "time": 185
        },
        {
            "date": "2024-10-24",
            "time": 163
        },
        {
            "date": "2024-10-25",
            "time": 176
        },
        {
            "date": "2024-10-25",
            "time": 124
        },
        {
            "date": "2024-10-25",
            "time": 163
        },
        {
            "date": "2024-10-27",
            "time": 142
        },
        {
            "date": "2024-10-28",
            "time": 177
        }
    ]
}
export const testLast30ActivitiesData = [
    {
        "resource_state": 2,
        "athlete": {
            "id": 145570628,
            "resource_state": 1
        },
        "name": "Morning Run",
        "distance": 11377.9,
        "moving_time": 4605,
        "elapsed_time": 4638,
        "total_elevation_gain": 71.4,
        "type": "Run",
        "sport_type": "Run",
        "workout_type": null,
        "id": 12767163446,
        "start_date": "2024-10-28T17:06:31Z",
        "start_date_local": "2024-10-28T10:06:31Z",
        "timezone": "(GMT-08:00) America/Los_Angeles",
        "utc_offset": -25200,
        "location_city": null,
        "location_state": null,
        "location_country": "United States",
        "achievement_count": 1,
        "kudos_count": 1,
        "comment_count": 0,
        "athlete_count": 1,
        "photo_count": 0,
        "map": {
            "id": "a12767163446",
            "summary_polyline": "iqklEfu{nU\\t@H\\`@fA^xAb@bEHhBJtICrC?|@Cb@?^KLK?}@AkDFiG?g@C]BKDEf@CJ[TMRCR?JZhADl@Cn@OrAW`AAZH^HNVVNXDLB\\ArAEj@Fn@ETC^G^Nh@BTA|@Mp@@PHZ?VIZMPYPEHEPCb@?RDPRZ\\^HPBRC\\Sj@ATFz@?v@@HHPDZAHCDC@M?GG?OVcBEsAR{@?WEWGQo@w@EKAS@_@HSDIf@_@FQ?IGiAHw@@q@C]Sw@@KRiAEm@B]Am@Bg@Ec@_@s@Y_@ESB[Pa@DUToBAcASu@O[AOBOFOf@e@Bi@BCDAf@AZBj@Gf@B`BBbBCtABrCCN@JLv@OAa@OcB?eCBMXFZBjAV|AFrAXZBpDt@bEr@p@RrDp@ZHx@JvA^pCd@tBb@lBXlDr@`AN`Ez@pJfBlHxA|E|@XHdBXtBb@`@DbAZtBb@nEr@lA\\zAj@VLHF@FI`@@RJJZLF?JCPa@\\i@d@_Al@aAj@uAl@mA@I_@POPIBEAmBaAs@[eC}@aBc@uE{@u@QaFy@{@Uu@KsBe@eDm@c@EoB[mIcBkEs@_Ew@}@Y{@OYAu@QoBYsCi@}D{@oB[OGe@Cs@Y{Bs@mBc@q@IwCy@}A[}Bo@]Eq@SgAMVHrCj@jHnBr@FvAVbAVdA`@vBr@fDp@x@Jr@LUOmAOgA[_Cc@q@SyBu@iBa@oB[}EuAi@IyAa@kASe@OIM[y@KOIE[CGCIy@QgAMWKi@]uAGIY@OGGa@K]_@g@Sk@]k@CEG?SF_@BMDEFAR@^H^@PALQv@?ZFTNRPFV@HFZr@PPTLN?TKFGJ[@[K_@Yk@MmA_@aAYWIOGEu@BGBCN@\\J\\@PUt@CN?NH^PTJFVBFB`@r@TVPDN?PGJKH]AWEU[s@Cg@Ki@c@}@g@k@u@AKGIOGE_@@YC]Oa@YMW_@[iBeCSe@YoAUg@WQa@M[UcC}Co@_A]_@_As@k@Sg@IPD",
            "resource_state": 2
        },
        "trainer": false,
        "commute": false,
        "manual": false,
        "private": false,
        "visibility": "everyone",
        "flagged": false,
        "gear_id": null,
        "start_latlng": [
            33.65328,
            -117.946835
        ],
        "end_latlng": [
            33.655726,
            -117.944543
        ],
        "average_speed": 2.471,
        "max_speed": 7.14,
        "has_heartrate": true,
        "average_heartrate": 160.7,
        "max_heartrate": 177,
        "heartrate_opt_out": false,
        "display_hide_heartrate_option": true,
        "elev_high": 29.2,
        "elev_low": 3.6,
        "upload_id": 13613107387,
        "upload_id_str": "13613107387",
        "external_id": "32A0B1A3-8C63-4DDD-AA41-333A2C5C5F61.fit",
        "from_accepted_tag": false,
        "pr_count": 1,
        "total_photo_count": 0,
        "has_kudoed": false
    },
    {
        "resource_state": 2,
        "athlete": {
            "id": 145570628,
            "resource_state": 1
        },
        "name": "Morning Weight Training",
        "distance": 0,
        "moving_time": 4037,
        "elapsed_time": 4037,
        "total_elevation_gain": 0,
        "type": "WeightTraining",
        "sport_type": "WeightTraining",
        "id": 12760433315,
        "start_date": "2024-10-27T17:39:05Z",
        "start_date_local": "2024-10-27T10:39:05Z",
        "timezone": "(GMT-07:00) America/Creston",
        "utc_offset": -25200,
        "location_city": null,
        "location_state": null,
        "location_country": "United States",
        "achievement_count": 0,
        "kudos_count": 1,
        "comment_count": 0,
        "athlete_count": 1,
        "photo_count": 0,
        "map": {
            "id": "a12760433315",
            "summary_polyline": "",
            "resource_state": 2
        },
        "trainer": true,
        "commute": false,
        "manual": false,
        "private": false,
        "visibility": "everyone",
        "flagged": false,
        "gear_id": null,
        "start_latlng": [],
        "end_latlng": [],
        "average_speed": 0,
        "max_speed": 0,
        "has_heartrate": true,
        "average_heartrate": 103,
        "max_heartrate": 142,
        "heartrate_opt_out": false,
        "display_hide_heartrate_option": true,
        "elev_high": 0,
        "elev_low": 0,
        "upload_id": 13605778291,
        "upload_id_str": "13605778291",
        "external_id": "D93DAE8E-BCC3-4334-B9FB-AAF65663A91F.fit",
        "from_accepted_tag": false,
        "pr_count": 0,
        "total_photo_count": 0,
        "has_kudoed": false
    },
    {
        "resource_state": 2,
        "athlete": {
            "id": 145570628,
            "resource_state": 1
        },
        "name": "Afternoon Run",
        "distance": 6505.8,
        "moving_time": 2882,
        "elapsed_time": 2946,
        "total_elevation_gain": 42.6,
        "type": "Run",
        "sport_type": "Run",
        "workout_type": null,
        "id": 12744379567,
        "start_date": "2024-10-25T21:53:10Z",
        "start_date_local": "2024-10-25T14:53:10Z",
        "timezone": "(GMT-08:00) America/Los_Angeles",
        "utc_offset": -25200,
        "location_city": null,
        "location_state": null,
        "location_country": "United States",
        "achievement_count": 0,
        "kudos_count": 1,
        "comment_count": 0,
        "athlete_count": 1,
        "photo_count": 0,
        "map": {
            "id": "a12744379567",
            "summary_polyline": "m|klE|m{nUv@dA\\XVLp@Pt@BTFb@GT?LEj@lAFFn@|AJf@Xv@Z|AThBAL@DC@s@Eo@@WDWN?F^NbC`@d@FrBf@zB^z@VpCp@pBl@vARlCj@tBv@nAZrAVTBfAVlAR`I`BzATnE|@tATrAXt@Jv@TvEt@hAZhBTl@Nz@PzFz@nCp@hCf@pARh@Np@H~Bf@jAT\\HRHn@LnBp@^PhAl@B?EIcAi@gBu@sDaA}AUmHuA]Cw@UkGqAcGaAiCe@YEuAYaCe@]Ek@OgBYaAWoCi@yCe@cCk@cC_@gBa@gGeAgC{@cAYcDo@MA[KsBe@sDcAyA]aAQUWOi@MYOIOBIAEGGU_@mCWgAO_@Qw@Y{@[g@Sm@g@y@CSe@kAQ[GS@@@BCAQHQNIHATBhAGZMHOB[Aa@G_@Sg@e@gA}AOY[c@[q@",
            "resource_state": 2
        },
        "trainer": false,
        "commute": false,
        "manual": false,
        "private": false,
        "visibility": "everyone",
        "flagged": false,
        "gear_id": null,
        "start_latlng": [
            33.654989,
            -117.944602
        ],
        "end_latlng": [
            33.655683,
            -117.944551
        ],
        "average_speed": 2.257,
        "max_speed": 4.28,
        "has_heartrate": true,
        "average_heartrate": 146.5,
        "max_heartrate": 163,
        "heartrate_opt_out": false,
        "display_hide_heartrate_option": true,
        "elev_high": 28.8,
        "elev_low": 2.6,
        "upload_id": 13588340040,
        "upload_id_str": "13588340040",
        "external_id": "93DD596B-0A10-4C29-A665-3D24ED8C4AF6.fit",
        "from_accepted_tag": false,
        "pr_count": 0,
        "total_photo_count": 0,
        "has_kudoed": false
    },
    {
        "resource_state": 2,
        "athlete": {
            "id": 145570628,
            "resource_state": 1
        },
        "name": "Morning Weight Training",
        "distance": 0,
        "moving_time": 3608,
        "elapsed_time": 3608,
        "total_elevation_gain": 0,
        "type": "WeightTraining",
        "sport_type": "WeightTraining",
        "id": 12743770698,
        "start_date": "2024-10-25T15:24:48Z",
        "start_date_local": "2024-10-25T08:24:48Z",
        "timezone": "(GMT-07:00) America/Creston",
        "utc_offset": -25200,
        "location_city": null,
        "location_state": null,
        "location_country": "United States",
        "achievement_count": 0,
        "kudos_count": 1,
        "comment_count": 0,
        "athlete_count": 1,
        "photo_count": 0,
        "map": {
            "id": "a12743770698",
            "summary_polyline": "",
            "resource_state": 2
        },
        "trainer": true,
        "commute": false,
        "manual": false,
        "private": false,
        "visibility": "everyone",
        "flagged": false,
        "gear_id": null,
        "start_latlng": [],
        "end_latlng": [],
        "average_speed": 0,
        "max_speed": 0,
        "has_heartrate": true,
        "average_heartrate": 88.1,
        "max_heartrate": 124,
        "heartrate_opt_out": false,
        "display_hide_heartrate_option": true,
        "elev_high": 0,
        "elev_low": 0,
        "upload_id": 13587688186,
        "upload_id_str": "13587688186",
        "external_id": "00C1EBE6-E4D0-442A-B9A4-9C9655385663.fit",
        "from_accepted_tag": false,
        "pr_count": 0,
        "total_photo_count": 0,
        "has_kudoed": false
    },
    {
        "resource_state": 2,
        "athlete": {
            "id": 145570628,
            "resource_state": 1
        },
        "name": "Evening Stair-Stepper",
        "distance": 0,
        "moving_time": 1379,
        "elapsed_time": 1379,
        "total_elevation_gain": 0,
        "type": "StairStepper",
        "sport_type": "StairStepper",
        "id": 12738166246,
        "start_date": "2024-10-25T01:15:32Z",
        "start_date_local": "2024-10-24T18:15:32Z",
        "timezone": "(GMT-07:00) America/Creston",
        "utc_offset": -25200,
        "location_city": null,
        "location_state": null,
        "location_country": "United States",
        "achievement_count": 0,
        "kudos_count": 1,
        "comment_count": 0,
        "athlete_count": 1,
        "photo_count": 0,
        "map": {
            "id": "a12738166246",
            "summary_polyline": "",
            "resource_state": 2
        },
        "trainer": true,
        "commute": false,
        "manual": false,
        "private": false,
        "visibility": "everyone",
        "flagged": false,
        "gear_id": null,
        "start_latlng": [],
        "end_latlng": [],
        "average_speed": 0,
        "max_speed": 0,
        "has_heartrate": true,
        "average_heartrate": 156.4,
        "max_heartrate": 176,
        "heartrate_opt_out": false,
        "display_hide_heartrate_option": true,
        "elev_high": 0,
        "elev_low": 0,
        "upload_id": 13581603298,
        "upload_id_str": "13581603298",
        "external_id": "B29B6192-2579-4EBE-8D71-C7901FB5AEA9.fit",
        "from_accepted_tag": false,
        "pr_count": 0,
        "total_photo_count": 0,
        "has_kudoed": false
    },
    {
        "resource_state": 2,
        "athlete": {
            "id": 145570628,
            "resource_state": 1
        },
        "name": "Afternoon Weight Training",
        "distance": 0,
        "moving_time": 5254,
        "elapsed_time": 5254,
        "total_elevation_gain": 0,
        "type": "WeightTraining",
        "sport_type": "WeightTraining",
        "id": 12738075027,
        "start_date": "2024-10-24T23:45:41Z",
        "start_date_local": "2024-10-24T16:45:41Z",
        "timezone": "(GMT-07:00) America/Creston",
        "utc_offset": -25200,
        "location_city": null,
        "location_state": null,
        "location_country": "United States",
        "achievement_count": 0,
        "kudos_count": 1,
        "comment_count": 0,
        "athlete_count": 1,
        "photo_count": 0,
        "map": {
            "id": "a12738075027",
            "summary_polyline": "",
            "resource_state": 2
        },
        "trainer": true,
        "commute": false,
        "manual": false,
        "private": false,
        "visibility": "everyone",
        "flagged": false,
        "gear_id": null,
        "start_latlng": [],
        "end_latlng": [],
        "average_speed": 0,
        "max_speed": 0,
        "has_heartrate": true,
        "average_heartrate": 117.9,
        "max_heartrate": 163,
        "heartrate_opt_out": false,
        "display_hide_heartrate_option": true,
        "elev_high": 0,
        "elev_low": 0,
        "upload_id": 13581505549,
        "upload_id_str": "13581505549",
        "external_id": "7E24B806-E708-41CB-A138-64C360BC0E5A.fit",
        "from_accepted_tag": false,
        "pr_count": 0,
        "total_photo_count": 0,
        "has_kudoed": false
    },
    {
        "resource_state": 2,
        "athlete": {
            "id": 145570628,
            "resource_state": 1
        },
        "name": "Afternoon Run",
        "distance": 5094.8,
        "moving_time": 1733,
        "elapsed_time": 1738,
        "total_elevation_gain": 16,
        "type": "Run",
        "sport_type": "Run",
        "workout_type": null,
        "id": 12736864481,
        "start_date": "2024-10-24T20:39:18Z",
        "start_date_local": "2024-10-24T13:39:18Z",
        "timezone": "(GMT-08:00) America/Los_Angeles",
        "utc_offset": -25200,
        "location_city": null,
        "location_state": null,
        "location_country": "United States",
        "achievement_count": 1,
        "kudos_count": 1,
        "comment_count": 0,
        "athlete_count": 1,
        "photo_count": 0,
        "map": {
            "id": "a12736864481",
            "summary_polyline": "}gklEfe|nUj@JxCn@r@TlFtAxDn@~DtA|ATXHrARbBb@pCj@|Bb@x@JR@j@Ph@Dh@Nt@L\\J~FdAf@LdBV`ATXBtCl@r@P|AR|Ch@zA\\fBTdDx@|Bb@dATxEz@dBd@l@V^Tv@LpAr@ZRb@PJ?FEHWNSFA?F]x@w@tAmBzD]f@GDUMQWAYD[EMEEwAc@sAg@i@OkBW{A]kBYk@Uc@Kq@K_@Ay@OwCo@_Ca@uCo@_AOaCg@_BWcDs@g@Gc@MoAQYKw@IeE{@kDk@k@OqDq@{@WwAQcDu@_BWsCo@oDu@mBWU@_BY",
            "resource_state": 2
        },
        "trainer": false,
        "commute": false,
        "manual": false,
        "private": false,
        "visibility": "everyone",
        "flagged": false,
        "gear_id": null,
        "start_latlng": [
            33.651348,
            -117.947823
        ],
        "end_latlng": [
            33.650559,
            -117.950557
        ],
        "average_speed": 2.94,
        "max_speed": 4.35,
        "has_heartrate": true,
        "average_heartrate": 173.7,
        "max_heartrate": 185,
        "heartrate_opt_out": false,
        "display_hide_heartrate_option": true,
        "elev_high": 24.6,
        "elev_low": 1.4,
        "upload_id": 13580218543,
        "upload_id_str": "13580218543",
        "external_id": "0FEF9395-46F8-4080-8A91-7088AA2CE828.fit",
        "from_accepted_tag": false,
        "pr_count": 1,
        "total_photo_count": 0,
        "has_kudoed": false
    },
    {
        "resource_state": 2,
        "athlete": {
            "id": 145570628,
            "resource_state": 1
        },
        "name": "Morning Stair-Stepper",
        "distance": 0,
        "moving_time": 869,
        "elapsed_time": 869,
        "total_elevation_gain": 0,
        "type": "StairStepper",
        "sport_type": "StairStepper",
        "id": 12726233708,
        "start_date": "2024-10-23T15:04:09Z",
        "start_date_local": "2024-10-23T08:04:09Z",
        "timezone": "(GMT-07:00) America/Creston",
        "utc_offset": -25200,
        "location_city": null,
        "location_state": null,
        "location_country": "United States",
        "achievement_count": 0,
        "kudos_count": 1,
        "comment_count": 0,
        "athlete_count": 1,
        "photo_count": 0,
        "map": {
            "id": "a12726233708",
            "summary_polyline": "",
            "resource_state": 2
        },
        "trainer": true,
        "commute": false,
        "manual": false,
        "private": false,
        "visibility": "everyone",
        "flagged": false,
        "gear_id": null,
        "start_latlng": [],
        "end_latlng": [],
        "average_speed": 0,
        "max_speed": 0,
        "has_heartrate": true,
        "average_heartrate": 154.6,
        "max_heartrate": 167,
        "heartrate_opt_out": false,
        "display_hide_heartrate_option": true,
        "elev_high": 0,
        "elev_low": 0,
        "upload_id": 13568863761,
        "upload_id_str": "13568863761",
        "external_id": "DBE6A1E8-6224-4641-A470-267602194A01.fit",
        "from_accepted_tag": false,
        "pr_count": 0,
        "total_photo_count": 0,
        "has_kudoed": false
    },
    {
        "resource_state": 2,
        "athlete": {
            "id": 145570628,
            "resource_state": 1
        },
        "name": "Morning Weight Training",
        "distance": 0,
        "moving_time": 3074,
        "elapsed_time": 3074,
        "total_elevation_gain": 0,
        "type": "WeightTraining",
        "sport_type": "WeightTraining",
        "id": 12726124449,
        "start_date": "2024-10-23T14:12:46Z",
        "start_date_local": "2024-10-23T07:12:46Z",
        "timezone": "(GMT-07:00) America/Creston",
        "utc_offset": -25200,
        "location_city": null,
        "location_state": null,
        "location_country": "United States",
        "achievement_count": 0,
        "kudos_count": 1,
        "comment_count": 0,
        "athlete_count": 1,
        "photo_count": 0,
        "map": {
            "id": "a12726124449",
            "summary_polyline": "",
            "resource_state": 2
        },
        "trainer": true,
        "commute": false,
        "manual": false,
        "private": false,
        "visibility": "everyone",
        "flagged": false,
        "gear_id": null,
        "start_latlng": [],
        "end_latlng": [],
        "average_speed": 0,
        "max_speed": 0,
        "has_heartrate": true,
        "average_heartrate": 104.9,
        "max_heartrate": 148,
        "heartrate_opt_out": false,
        "display_hide_heartrate_option": true,
        "elev_high": 0,
        "elev_low": 0,
        "upload_id": 13568745974,
        "upload_id_str": "13568745974",
        "external_id": "914AAA10-51DC-4B04-98A0-5E38D6C0FE09.fit",
        "from_accepted_tag": false,
        "pr_count": 0,
        "total_photo_count": 0,
        "has_kudoed": false
    },
    {
        "resource_state": 2,
        "athlete": {
            "id": 145570628,
            "resource_state": 1
        },
        "name": "Afternoon Run",
        "distance": 9119.1,
        "moving_time": 3556,
        "elapsed_time": 3565,
        "total_elevation_gain": 50.6,
        "type": "Run",
        "sport_type": "Run",
        "workout_type": null,
        "id": 12712841880,
        "start_date": "2024-10-21T22:37:45Z",
        "start_date_local": "2024-10-21T15:37:45Z",
        "timezone": "(GMT-08:00) America/Los_Angeles",
        "utc_offset": -25200,
        "location_city": null,
        "location_state": null,
        "location_country": "United States",
        "achievement_count": 3,
        "kudos_count": 1,
        "comment_count": 0,
        "athlete_count": 1,
        "photo_count": 0,
        "map": {
            "id": "a12712841880",
            "summary_polyline": "wwllEviznUYMIAoD?q@FiB?YAk@KMG]Yq@qAcA}Aa@]o@QgAFg@LUJ_BdAg@Xc@Li@Jc@@kAAqDe@_@DYJc@Z[`@Y~@Gb@Ab@DhA?|@SxDs@jFWpCOxASz@FHNDM@MDEDS`@CTBJJHbCj@fC\\hBZ\\BjAVjC`@lDn@^LvARtBd@lB\\TBRA`@BfAVj@Tt@Nv@T~Ex@|A^pEv@bDp@bBV|Bf@l@FxAZhIzAtCn@j@BjCl@x@LxA\\~EpAlA^z@LxCh@nDnA`AT\\D`B\\x@L`Dn@|B`@bCh@tI|AlCj@xF`ApA\\jAN~Dt@~@LrJnB`@JhANjF`A`AVb@FbCt@|@\\x@b@\\TfAd@B?DCL]LMFC?FcDnG_@n@[l@EFE@WMQYASBc@CIIG}B{@oBe@a@EgASk@GeB[iAa@sAQaB]oB]}Bg@cGeAwEeAsASoDs@eAO{@U}AYq@Iq@QqDs@kAOgAYcDk@kE}@UCgEaAuB]WKeB[gFw@WAYEs@?mAWi@GUSCI?gAIwGEu@UqCGUEEc@CGEMcAEMUaA]oAMOu@_Ba@o@GAOF_@@o@MU@O?i@S]W[Ka@k@a@q@YWY_@Wg@Os@",
            "resource_state": 2
        },
        "trainer": false,
        "commute": false,
        "manual": false,
        "private": false,
        "visibility": "everyone",
        "flagged": false,
        "gear_id": null,
        "start_latlng": [
            33.65624581463635,
            -117.94091873802245
        ],
        "end_latlng": [
            33.65571121685207,
            -117.94453628361225
        ],
        "average_speed": 2.564,
        "max_speed": 3.766,
        "has_heartrate": true,
        "average_heartrate": 167.8,
        "max_heartrate": 179,
        "heartrate_opt_out": false,
        "display_hide_heartrate_option": true,
        "elev_high": 29,
        "elev_low": 2.2,
        "upload_id": 13554521759,
        "upload_id_str": "13554521759",
        "external_id": "03449DE3-3498-47E2-8292-30F8C1D6DD8C.fit",
        "from_accepted_tag": false,
        "pr_count": 2,
        "total_photo_count": 0,
        "has_kudoed": false
    },
    {
        "resource_state": 2,
        "athlete": {
            "id": 145570628,
            "resource_state": 1
        },
        "name": "Lunch Stair-Stepper",
        "distance": 0,
        "moving_time": 1837,
        "elapsed_time": 1837,
        "total_elevation_gain": 0,
        "type": "StairStepper",
        "sport_type": "StairStepper",
        "id": 12711749665,
        "start_date": "2024-10-21T19:59:25Z",
        "start_date_local": "2024-10-21T12:59:25Z",
        "timezone": "(GMT-07:00) America/Creston",
        "utc_offset": -25200,
        "location_city": null,
        "location_state": null,
        "location_country": "United States",
        "achievement_count": 0,
        "kudos_count": 1,
        "comment_count": 0,
        "athlete_count": 1,
        "photo_count": 0,
        "map": {
            "id": "a12711749665",
            "summary_polyline": "",
            "resource_state": 2
        },
        "trainer": true,
        "commute": false,
        "manual": false,
        "private": false,
        "visibility": "everyone",
        "flagged": false,
        "gear_id": null,
        "start_latlng": [],
        "end_latlng": [],
        "average_speed": 0,
        "max_speed": 0,
        "has_heartrate": true,
        "average_heartrate": 153.9,
        "max_heartrate": 173,
        "heartrate_opt_out": false,
        "display_hide_heartrate_option": true,
        "elev_high": 0,
        "elev_low": 0,
        "upload_id": 13553368105,
        "upload_id_str": "13553368105",
        "external_id": "2D75EF08-810E-4946-B98A-0477DC9E702E.fit",
        "from_accepted_tag": false,
        "pr_count": 0,
        "total_photo_count": 0,
        "has_kudoed": false
    },
    {
        "resource_state": 2,
        "athlete": {
            "id": 145570628,
            "resource_state": 1
        },
        "name": "Lunch Weight Training",
        "distance": 0,
        "moving_time": 3173,
        "elapsed_time": 3173,
        "total_elevation_gain": 0,
        "type": "WeightTraining",
        "sport_type": "WeightTraining",
        "id": 12711569461,
        "start_date": "2024-10-21T19:05:38Z",
        "start_date_local": "2024-10-21T12:05:38Z",
        "timezone": "(GMT-07:00) America/Creston",
        "utc_offset": -25200,
        "location_city": null,
        "location_state": null,
        "location_country": "United States",
        "achievement_count": 0,
        "kudos_count": 1,
        "comment_count": 0,
        "athlete_count": 1,
        "photo_count": 0,
        "map": {
            "id": "a12711569461",
            "summary_polyline": "",
            "resource_state": 2
        },
        "trainer": true,
        "commute": false,
        "manual": false,
        "private": false,
        "visibility": "everyone",
        "flagged": false,
        "gear_id": null,
        "start_latlng": [],
        "end_latlng": [],
        "average_speed": 0,
        "max_speed": 0,
        "has_heartrate": true,
        "average_heartrate": 113.3,
        "max_heartrate": 159,
        "heartrate_opt_out": false,
        "display_hide_heartrate_option": true,
        "elev_high": 0,
        "elev_low": 0,
        "upload_id": 13553176563,
        "upload_id_str": "13553176563",
        "external_id": "294ACB7B-CA7B-42D8-BE5F-2670E6500953.fit",
        "from_accepted_tag": false,
        "pr_count": 0,
        "total_photo_count": 0,
        "has_kudoed": false
    },
    {
        "resource_state": 2,
        "athlete": {
            "id": 145570628,
            "resource_state": 1
        },
        "name": "Lunch Stair-Stepper",
        "distance": 0,
        "moving_time": 1677,
        "elapsed_time": 1677,
        "total_elevation_gain": 0,
        "type": "StairStepper",
        "sport_type": "StairStepper",
        "id": 12704083211,
        "start_date": "2024-10-20T18:40:55Z",
        "start_date_local": "2024-10-20T11:40:55Z",
        "timezone": "(GMT-07:00) America/Creston",
        "utc_offset": -25200,
        "location_city": null,
        "location_state": null,
        "location_country": "United States",
        "achievement_count": 0,
        "kudos_count": 1,
        "comment_count": 0,
        "athlete_count": 1,
        "photo_count": 0,
        "map": {
            "id": "a12704083211",
            "summary_polyline": "",
            "resource_state": 2
        },
        "trainer": true,
        "commute": false,
        "manual": false,
        "private": false,
        "visibility": "everyone",
        "flagged": false,
        "gear_id": null,
        "start_latlng": [],
        "end_latlng": [],
        "average_speed": 0,
        "max_speed": 0,
        "has_heartrate": true,
        "average_heartrate": 159.9,
        "max_heartrate": 171,
        "heartrate_opt_out": false,
        "display_hide_heartrate_option": true,
        "elev_high": 0,
        "elev_low": 0,
        "upload_id": 13545069686,
        "upload_id_str": "13545069686",
        "external_id": "2F67E0AD-810D-417A-8B38-EA8C1242C188.fit",
        "from_accepted_tag": false,
        "pr_count": 0,
        "total_photo_count": 0,
        "has_kudoed": false
    },
    {
        "resource_state": 2,
        "athlete": {
            "id": 145570628,
            "resource_state": 1
        },
        "name": "Morning Weight Training",
        "distance": 0,
        "moving_time": 4023,
        "elapsed_time": 4023,
        "total_elevation_gain": 0,
        "type": "WeightTraining",
        "sport_type": "WeightTraining",
        "id": 12703924344,
        "start_date": "2024-10-20T17:33:44Z",
        "start_date_local": "2024-10-20T10:33:44Z",
        "timezone": "(GMT-07:00) America/Creston",
        "utc_offset": -25200,
        "location_city": null,
        "location_state": null,
        "location_country": "United States",
        "achievement_count": 0,
        "kudos_count": 1,
        "comment_count": 0,
        "athlete_count": 1,
        "photo_count": 0,
        "map": {
            "id": "a12703924344",
            "summary_polyline": "",
            "resource_state": 2
        },
        "trainer": true,
        "commute": false,
        "manual": false,
        "private": false,
        "visibility": "everyone",
        "flagged": false,
        "gear_id": null,
        "start_latlng": [],
        "end_latlng": [],
        "average_speed": 0,
        "max_speed": 0,
        "has_heartrate": true,
        "average_heartrate": 113.8,
        "max_heartrate": 155,
        "heartrate_opt_out": false,
        "display_hide_heartrate_option": true,
        "elev_high": 0,
        "elev_low": 0,
        "upload_id": 13544897599,
        "upload_id_str": "13544897599",
        "external_id": "FC2D1DE0-345F-4192-8EB5-FA2EBCF482DB.fit",
        "from_accepted_tag": false,
        "pr_count": 0,
        "total_photo_count": 0,
        "has_kudoed": false
    },
    {
        "resource_state": 2,
        "athlete": {
            "id": 145570628,
            "resource_state": 1
        },
        "name": "Evening HIIT",
        "distance": 0,
        "moving_time": 1043,
        "elapsed_time": 1043,
        "total_elevation_gain": 0,
        "type": "Workout",
        "sport_type": "HighIntensityIntervalTraining",
        "id": 12689125780,
        "start_date": "2024-10-19T02:13:45Z",
        "start_date_local": "2024-10-18T19:13:45Z",
        "timezone": "(GMT-07:00) America/Creston",
        "utc_offset": -25200,
        "location_city": null,
        "location_state": null,
        "location_country": "United States",
        "achievement_count": 0,
        "kudos_count": 1,
        "comment_count": 0,
        "athlete_count": 1,
        "photo_count": 0,
        "map": {
            "id": "a12689125780",
            "summary_polyline": "",
            "resource_state": 2
        },
        "trainer": true,
        "commute": false,
        "manual": false,
        "private": false,
        "visibility": "everyone",
        "flagged": false,
        "gear_id": null,
        "start_latlng": [],
        "end_latlng": [],
        "average_speed": 0,
        "max_speed": 0,
        "has_heartrate": true,
        "average_heartrate": 140.4,
        "max_heartrate": 171,
        "heartrate_opt_out": false,
        "display_hide_heartrate_option": true,
        "elev_high": 0,
        "elev_low": 0,
        "upload_id": 13528961553,
        "upload_id_str": "13528961553",
        "external_id": "1BFC97B1-F542-4FEE-8F3D-DC49979809A2.fit",
        "from_accepted_tag": false,
        "pr_count": 0,
        "total_photo_count": 0,
        "has_kudoed": false
    },
    {
        "resource_state": 2,
        "athlete": {
            "id": 145570628,
            "resource_state": 1
        },
        "name": "Morning Weight Training",
        "distance": 0,
        "moving_time": 4080,
        "elapsed_time": 4080,
        "total_elevation_gain": 0,
        "type": "WeightTraining",
        "sport_type": "WeightTraining",
        "id": 12685713571,
        "start_date": "2024-10-18T14:19:30Z",
        "start_date_local": "2024-10-18T07:19:30Z",
        "timezone": "(GMT-07:00) America/Creston",
        "utc_offset": -25200,
        "location_city": null,
        "location_state": null,
        "location_country": "United States",
        "achievement_count": 0,
        "kudos_count": 1,
        "comment_count": 0,
        "athlete_count": 1,
        "photo_count": 0,
        "map": {
            "id": "a12685713571",
            "summary_polyline": "",
            "resource_state": 2
        },
        "trainer": true,
        "commute": false,
        "manual": false,
        "private": false,
        "visibility": "everyone",
        "flagged": false,
        "gear_id": null,
        "start_latlng": [],
        "end_latlng": [],
        "average_speed": 0,
        "max_speed": 0,
        "has_heartrate": true,
        "average_heartrate": 101.4,
        "max_heartrate": 150,
        "heartrate_opt_out": false,
        "display_hide_heartrate_option": true,
        "elev_high": 0,
        "elev_low": 0,
        "upload_id": 13525309003,
        "upload_id_str": "13525309003",
        "external_id": "D713EC3B-29CB-40BA-9C9A-C21053E31E3C.fit",
        "from_accepted_tag": false,
        "pr_count": 0,
        "total_photo_count": 0,
        "has_kudoed": false
    },
    {
        "resource_state": 2,
        "athlete": {
            "id": 145570628,
            "resource_state": 1
        },
        "name": "Lunch Run",
        "distance": 3707.3,
        "moving_time": 1522,
        "elapsed_time": 1534,
        "total_elevation_gain": 28.2,
        "type": "Run",
        "sport_type": "Run",
        "workout_type": null,
        "id": 12671837579,
        "start_date": "2024-10-16T18:09:55Z",
        "start_date_local": "2024-10-16T11:09:55Z",
        "timezone": "(GMT-08:00) America/Los_Angeles",
        "utc_offset": -25200,
        "location_city": null,
        "location_state": null,
        "location_country": "United States",
        "achievement_count": 0,
        "kudos_count": 1,
        "comment_count": 0,
        "athlete_count": 1,
        "photo_count": 0,
        "map": {
            "id": "a12671837579",
            "summary_polyline": "}vllEliznUo@Cy@Ac@BsAAuBDs@A_AKWKY]cAcB_AsA[U_@GeABk@Lg@ToBnAq@Vw@NmA?qDi@i@@e@N]TQRQ`@IVGh@Cl@@xCS`CUrAM~Ao@jFSrBWfAWf@EV@FFDz@PjHlAbMvBhHxAj@J^BR?xAR\\N|Bl@xB`@hATfBZxAZtB\\f@L~Dp@j@PxCf@h@LL@|@RxAVfAT~Cj@L?PMLAb@C`@?\\ARGBI]uDIg@S]s@eB",
            "resource_state": 2
        },
        "trainer": false,
        "commute": false,
        "manual": false,
        "private": false,
        "visibility": "everyone",
        "flagged": false,
        "gear_id": null,
        "start_latlng": [
            33.65616333670914,
            -117.94095528312027
        ],
        "end_latlng": [
            33.65317049436271,
            -117.9469532892108
        ],
        "average_speed": 2.436,
        "max_speed": 3.688,
        "has_heartrate": true,
        "average_heartrate": 148,
        "max_heartrate": 166,
        "heartrate_opt_out": false,
        "display_hide_heartrate_option": true,
        "elev_high": 28.6,
        "elev_low": 5.2,
        "upload_id": 13510457126,
        "upload_id_str": "13510457126",
        "external_id": "324329C8-6FA3-4460-80C8-A7116EC93777.fit",
        "from_accepted_tag": false,
        "pr_count": 0,
        "total_photo_count": 0,
        "has_kudoed": false
    },
    {
        "resource_state": 2,
        "athlete": {
            "id": 145570628,
            "resource_state": 1
        },
        "name": "Afternoon Stair-Stepper",
        "distance": 0,
        "moving_time": 1231,
        "elapsed_time": 1231,
        "total_elevation_gain": 0,
        "type": "StairStepper",
        "sport_type": "StairStepper",
        "id": 12665310993,
        "start_date": "2024-10-15T22:54:42Z",
        "start_date_local": "2024-10-15T15:54:42Z",
        "timezone": "(GMT-07:00) America/Creston",
        "utc_offset": -25200,
        "location_city": null,
        "location_state": null,
        "location_country": "United States",
        "achievement_count": 0,
        "kudos_count": 1,
        "comment_count": 0,
        "athlete_count": 1,
        "photo_count": 0,
        "map": {
            "id": "a12665310993",
            "summary_polyline": "",
            "resource_state": 2
        },
        "trainer": true,
        "commute": false,
        "manual": false,
        "private": false,
        "visibility": "everyone",
        "flagged": false,
        "gear_id": null,
        "start_latlng": [],
        "end_latlng": [],
        "average_speed": 0,
        "max_speed": 0,
        "has_heartrate": true,
        "average_heartrate": 160,
        "max_heartrate": 173,
        "heartrate_opt_out": false,
        "display_hide_heartrate_option": true,
        "elev_high": 0,
        "elev_low": 0,
        "upload_id": 13503490258,
        "upload_id_str": "13503490258",
        "external_id": "D2BE4A06-44EB-4B3E-8F20-77EE58B6DB95.fit",
        "from_accepted_tag": false,
        "pr_count": 0,
        "total_photo_count": 0,
        "has_kudoed": false
    },
    {
        "resource_state": 2,
        "athlete": {
            "id": 145570628,
            "resource_state": 1
        },
        "name": "Afternoon Weight Training",
        "distance": 0,
        "moving_time": 3524,
        "elapsed_time": 3524,
        "total_elevation_gain": 0,
        "type": "WeightTraining",
        "sport_type": "WeightTraining",
        "id": 12665203211,
        "start_date": "2024-10-15T21:55:49Z",
        "start_date_local": "2024-10-15T14:55:49Z",
        "timezone": "(GMT-07:00) America/Creston",
        "utc_offset": -25200,
        "location_city": null,
        "location_state": null,
        "location_country": "United States",
        "achievement_count": 0,
        "kudos_count": 1,
        "comment_count": 0,
        "athlete_count": 1,
        "photo_count": 0,
        "map": {
            "id": "a12665203211",
            "summary_polyline": "",
            "resource_state": 2
        },
        "trainer": true,
        "commute": false,
        "manual": false,
        "private": false,
        "visibility": "everyone",
        "flagged": false,
        "gear_id": null,
        "start_latlng": [],
        "end_latlng": [],
        "average_speed": 0,
        "max_speed": 0,
        "has_heartrate": true,
        "average_heartrate": 116.1,
        "max_heartrate": 155,
        "heartrate_opt_out": false,
        "display_hide_heartrate_option": true,
        "elev_high": 0,
        "elev_low": 0,
        "upload_id": 13503377785,
        "upload_id_str": "13503377785",
        "external_id": "E535D493-5B13-44C0-AF14-B1F24CD96950.fit",
        "from_accepted_tag": false,
        "pr_count": 0,
        "total_photo_count": 0,
        "has_kudoed": false
    },
    {
        "resource_state": 2,
        "athlete": {
            "id": 145570628,
            "resource_state": 1
        },
        "name": "Morning Walk",
        "distance": 1642.7,
        "moving_time": 1353,
        "elapsed_time": 1353,
        "total_elevation_gain": 0,
        "type": "Walk",
        "sport_type": "Walk",
        "id": 12662960225,
        "start_date": "2024-10-15T17:02:33Z",
        "start_date_local": "2024-10-15T10:02:33Z",
        "timezone": "(GMT-07:00) America/Creston",
        "utc_offset": -25200,
        "location_city": null,
        "location_state": null,
        "location_country": "United States",
        "achievement_count": 0,
        "kudos_count": 1,
        "comment_count": 0,
        "athlete_count": 1,
        "photo_count": 0,
        "map": {
            "id": "a12662960225",
            "summary_polyline": "",
            "resource_state": 2
        },
        "trainer": true,
        "commute": false,
        "manual": false,
        "private": false,
        "visibility": "everyone",
        "flagged": false,
        "gear_id": null,
        "start_latlng": [],
        "end_latlng": [],
        "average_speed": 1.214,
        "max_speed": 2.874,
        "has_heartrate": true,
        "average_heartrate": 154.4,
        "max_heartrate": 164,
        "heartrate_opt_out": false,
        "display_hide_heartrate_option": true,
        "elev_high": 0,
        "elev_low": 0,
        "upload_id": 13501013195,
        "upload_id_str": "13501013195",
        "external_id": "FEB87381-9A09-4958-A7A9-EF78F6905383.fit",
        "from_accepted_tag": false,
        "pr_count": 0,
        "total_photo_count": 0,
        "has_kudoed": false
    },
    {
        "resource_state": 2,
        "athlete": {
            "id": 145570628,
            "resource_state": 1
        },
        "name": "Morning Run",
        "distance": 4045.3,
        "moving_time": 1724,
        "elapsed_time": 1835,
        "total_elevation_gain": 0,
        "type": "Run",
        "sport_type": "Run",
        "workout_type": null,
        "id": 12662736103,
        "start_date": "2024-10-15T16:30:51Z",
        "start_date_local": "2024-10-15T09:30:51Z",
        "timezone": "(GMT-07:00) America/Creston",
        "utc_offset": -25200,
        "location_city": null,
        "location_state": null,
        "location_country": "United States",
        "achievement_count": 0,
        "kudos_count": 1,
        "comment_count": 0,
        "athlete_count": 1,
        "photo_count": 0,
        "map": {
            "id": "a12662736103",
            "summary_polyline": "",
            "resource_state": 2
        },
        "trainer": true,
        "commute": false,
        "manual": false,
        "private": false,
        "visibility": "everyone",
        "flagged": false,
        "gear_id": null,
        "start_latlng": [],
        "end_latlng": [],
        "average_speed": 2.346,
        "max_speed": 3.372,
        "has_heartrate": true,
        "average_heartrate": 155.5,
        "max_heartrate": 174,
        "heartrate_opt_out": false,
        "display_hide_heartrate_option": true,
        "elev_high": 0,
        "elev_low": 0,
        "upload_id": 13500777122,
        "upload_id_str": "13500777122",
        "external_id": "B116A691-2941-41FE-8386-D81341BCD7E5.fit",
        "from_accepted_tag": false,
        "pr_count": 0,
        "total_photo_count": 0,
        "has_kudoed": false
    },
    {
        "resource_state": 2,
        "athlete": {
            "id": 145570628,
            "resource_state": 1
        },
        "name": "Morning Weight Training",
        "distance": 0,
        "moving_time": 3905,
        "elapsed_time": 3905,
        "total_elevation_gain": 0,
        "type": "WeightTraining",
        "sport_type": "WeightTraining",
        "id": 12653755759,
        "start_date": "2024-10-14T14:19:02Z",
        "start_date_local": "2024-10-14T07:19:02Z",
        "timezone": "(GMT-07:00) America/Creston",
        "utc_offset": -25200,
        "location_city": null,
        "location_state": null,
        "location_country": "United States",
        "achievement_count": 0,
        "kudos_count": 1,
        "comment_count": 0,
        "athlete_count": 1,
        "photo_count": 0,
        "map": {
            "id": "a12653755759",
            "summary_polyline": "",
            "resource_state": 2
        },
        "trainer": true,
        "commute": false,
        "manual": false,
        "private": false,
        "visibility": "everyone",
        "flagged": false,
        "gear_id": null,
        "start_latlng": [],
        "end_latlng": [],
        "average_speed": 0,
        "max_speed": 0,
        "has_heartrate": true,
        "average_heartrate": 100.5,
        "max_heartrate": 153,
        "heartrate_opt_out": false,
        "display_hide_heartrate_option": true,
        "elev_high": 0,
        "elev_low": 0,
        "upload_id": 13491158761,
        "upload_id_str": "13491158761",
        "external_id": "7F0B23F0-8C45-4718-BA48-9D294D5715B5.fit",
        "from_accepted_tag": false,
        "pr_count": 0,
        "total_photo_count": 0,
        "has_kudoed": false
    },
    {
        "resource_state": 2,
        "athlete": {
            "id": 145570628,
            "resource_state": 1
        },
        "name": "Afternoon Run",
        "distance": 9056.6,
        "moving_time": 3546,
        "elapsed_time": 4057,
        "total_elevation_gain": 52.6,
        "type": "Run",
        "sport_type": "Run",
        "workout_type": null,
        "id": 12649387260,
        "start_date": "2024-10-13T20:46:49Z",
        "start_date_local": "2024-10-13T13:46:49Z",
        "timezone": "(GMT-08:00) America/Los_Angeles",
        "utc_offset": -25200,
        "location_city": null,
        "location_state": null,
        "location_country": "United States",
        "achievement_count": 1,
        "kudos_count": 1,
        "comment_count": 3,
        "athlete_count": 1,
        "photo_count": 0,
        "map": {
            "id": "a12649387260",
            "summary_polyline": "yuklEnq{nUFs@DeADCLVl@~ATf@PTTl@Vb@\\z@Pn@Vp@^jAHzAJdAJvADhEFh@Cf@BfCG~B@\\AxAGNQBmACkCAeAB[BaCEwB@MDCDGh@GHSPGNEN?R\\lA@v@CZMf@El@YjAAXDRFPXVPTJXDXGn@@h@Gr@B\\MtAPv@Dh@ANIVEf@D^@d@Mb@e@f@IVAX?VDRJPRRXd@F^WfA?RDv@Ap@DNLP@\\CHCBSACACG@SRcAAUBWG[?_@BQRi@@WKi@[]Wa@Kg@@SDIJO`@_@HUBS?SKq@Ls@@[Gu@Qs@TuAAs@Dg@C_@Fs@EOMYq@q@IQ@]Ru@ZkCGaAIg@KWEO@[HO^]DIFa@JIbA@`@Cp@DvA?rBEn@@fBApBFd@GBCCEAo@Ik@A[AaC@MDCH?bCd@fADzAZv@HvB^j@NfF~@x@TdAP\\JxB^dB^hIzAnCd@RFvDp@|A^`F|@vDx@bFz@RFfFdAp@J~Dx@fANt@TxAX\\B`B\\lBXhBj@dAh@HFDLE\\BVFHXHP?Xs@pBoDb@{@HWf@aA@EG?g@f@KBm@a@k@UaAi@mAc@gCu@wFeAkAQkBa@c@Gg@OsGsAaCc@gC]{@UkCe@uA[eB[k@Mq@KoCk@eBYcFcAaBUgE_AWCuAYoDo@yBq@{@]sFcAk@SwBg@[Es@YgBc@aBUuCs@iAM_Cc@BADBL@bAMpADLE@QE{@O}@@]K]U]Eg@[y@w@aBIKSg@KQ?LQRs@?GAWS{@I[GUK[QOOeAqBg@g@",
            "resource_state": 2
        },
        "trainer": false,
        "commute": false,
        "manual": false,
        "private": false,
        "visibility": "everyone",
        "flagged": false,
        "gear_id": null,
        "start_latlng": [
            33.65542992018163,
            -117.94422539882362
        ],
        "end_latlng": [
            33.655287930741906,
            -117.94420561753213
        ],
        "average_speed": 2.554,
        "max_speed": 7.79,
        "has_heartrate": true,
        "average_heartrate": 168.5,
        "max_heartrate": 183,
        "heartrate_opt_out": false,
        "display_hide_heartrate_option": true,
        "elev_high": 29.2,
        "elev_low": 2,
        "upload_id": 13486396545,
        "upload_id_str": "13486396545",
        "external_id": "D48DEE31-478C-4D74-BDB6-9FEC166F19B2.fit",
        "from_accepted_tag": false,
        "pr_count": 0,
        "total_photo_count": 0,
        "has_kudoed": false
    },
    {
        "resource_state": 2,
        "athlete": {
            "id": 145570628,
            "resource_state": 1
        },
        "name": "Morning Stair-Stepper",
        "distance": 0,
        "moving_time": 1214,
        "elapsed_time": 1214,
        "total_elevation_gain": 0,
        "type": "StairStepper",
        "sport_type": "StairStepper",
        "id": 12647920228,
        "start_date": "2024-10-13T16:46:26Z",
        "start_date_local": "2024-10-13T09:46:26Z",
        "timezone": "(GMT-07:00) America/Creston",
        "utc_offset": -25200,
        "location_city": null,
        "location_state": null,
        "location_country": "United States",
        "achievement_count": 0,
        "kudos_count": 1,
        "comment_count": 0,
        "athlete_count": 1,
        "photo_count": 0,
        "map": {
            "id": "a12647920228",
            "summary_polyline": "",
            "resource_state": 2
        },
        "trainer": true,
        "commute": false,
        "manual": false,
        "private": false,
        "visibility": "everyone",
        "flagged": false,
        "gear_id": null,
        "start_latlng": [],
        "end_latlng": [],
        "average_speed": 0,
        "max_speed": 0,
        "has_heartrate": true,
        "average_heartrate": 162.8,
        "max_heartrate": 175,
        "heartrate_opt_out": false,
        "display_hide_heartrate_option": true,
        "elev_high": 0,
        "elev_low": 0,
        "upload_id": 13484799288,
        "upload_id_str": "13484799288",
        "external_id": "6661E379-7AAA-4787-9D94-86B30E0DAE89.fit",
        "from_accepted_tag": false,
        "pr_count": 0,
        "total_photo_count": 0,
        "has_kudoed": false
    },
    {
        "resource_state": 2,
        "athlete": {
            "id": 145570628,
            "resource_state": 1
        },
        "name": "Morning Weight Training",
        "distance": 0,
        "moving_time": 3779,
        "elapsed_time": 3779,
        "total_elevation_gain": 0,
        "type": "WeightTraining",
        "sport_type": "WeightTraining",
        "id": 12647920230,
        "start_date": "2024-10-13T15:43:19Z",
        "start_date_local": "2024-10-13T08:43:19Z",
        "timezone": "(GMT-07:00) America/Creston",
        "utc_offset": -25200,
        "location_city": null,
        "location_state": null,
        "location_country": "United States",
        "achievement_count": 0,
        "kudos_count": 1,
        "comment_count": 0,
        "athlete_count": 1,
        "photo_count": 0,
        "map": {
            "id": "a12647920230",
            "summary_polyline": "",
            "resource_state": 2
        },
        "trainer": true,
        "commute": false,
        "manual": false,
        "private": false,
        "visibility": "everyone",
        "flagged": false,
        "gear_id": null,
        "start_latlng": [],
        "end_latlng": [],
        "average_speed": 0,
        "max_speed": 0,
        "has_heartrate": true,
        "average_heartrate": 114.8,
        "max_heartrate": 154,
        "heartrate_opt_out": false,
        "display_hide_heartrate_option": true,
        "elev_high": 0,
        "elev_low": 0,
        "upload_id": 13484799299,
        "upload_id_str": "13484799299",
        "external_id": "3AD8D7D7-5A43-4021-A1AF-C5F58A831149.fit",
        "from_accepted_tag": false,
        "pr_count": 0,
        "total_photo_count": 0,
        "has_kudoed": false
    },
    {
        "resource_state": 2,
        "athlete": {
            "id": 145570628,
            "resource_state": 1
        },
        "name": "Afternoon Run",
        "distance": 5953.8,
        "moving_time": 2591,
        "elapsed_time": 2604,
        "total_elevation_gain": 36.2,
        "type": "Run",
        "sport_type": "Run",
        "workout_type": null,
        "id": 12632243522,
        "start_date": "2024-10-11T21:22:24Z",
        "start_date_local": "2024-10-11T14:22:24Z",
        "timezone": "(GMT-08:00) America/Los_Angeles",
        "utc_offset": -25200,
        "location_city": null,
        "location_state": null,
        "location_country": "United States",
        "achievement_count": 1,
        "kudos_count": 1,
        "comment_count": 0,
        "athlete_count": 1,
        "photo_count": 0,
        "map": {
            "id": "a12632243522",
            "summary_polyline": "yiklElb|nUZbALNvDt@^D~DlAjB`@NHV@|A^r@HpAf@vAb@|Bd@nBXlBd@l@FlDl@t@RhAPrE~@f@Ff@LrB^p@Pp@HbAT|AX`ARt@J~Bf@|@NV@|Bf@dM~Bf@NxGnA|@Tt@XvAb@fAh@RNrAn@J?HYVYBA?Bc@dAsAjCgB~CGFE@c@UEIASFYCOIKk@OkAe@QMaAWa@Gi@M{@Ou@I{Bc@u@W_AMkAUq@QyCi@uBc@iAQa@MUC_Dq@q@G_@M_AOgB_@wDo@_AWc@G}Be@wAUi@OcDg@YIyCo@cAOSGSA_AUqAQa@OkASwA_@eDo@aBYk@OwAUWDaDg@eAGq@Oq@GMGGMMmJ_@}EQ{@Ea@Qa@Im@iA_DQWw@OS[ECWJO@WAa@GSDGAs@K]QUSOQQ]k@u@",
            "resource_state": 2
        },
        "trainer": false,
        "commute": false,
        "manual": false,
        "private": false,
        "visibility": "everyone",
        "flagged": false,
        "gear_id": null,
        "start_latlng": [
            33.65170701406896,
            -117.94747162610292
        ],
        "end_latlng": [
            33.65502926521003,
            -117.9444838128984
        ],
        "average_speed": 2.298,
        "max_speed": 3.864,
        "has_heartrate": true,
        "average_heartrate": 154.8,
        "max_heartrate": 170,
        "heartrate_opt_out": false,
        "display_hide_heartrate_option": true,
        "elev_high": 29,
        "elev_low": 2.8,
        "upload_id": 13467887511,
        "upload_id_str": "13467887511",
        "external_id": "D67D2F6D-1A1C-479B-92B7-6EDB7ABE29A1.fit",
        "from_accepted_tag": false,
        "pr_count": 0,
        "total_photo_count": 0,
        "has_kudoed": false
    },
    {
        "resource_state": 2,
        "athlete": {
            "id": 145570628,
            "resource_state": 1
        },
        "name": "Morning Weight Training",
        "distance": 0,
        "moving_time": 3627,
        "elapsed_time": 3627,
        "total_elevation_gain": 0,
        "type": "WeightTraining",
        "sport_type": "WeightTraining",
        "id": 12631351782,
        "start_date": "2024-10-11T17:49:10Z",
        "start_date_local": "2024-10-11T10:49:10Z",
        "timezone": "(GMT-07:00) America/Creston",
        "utc_offset": -25200,
        "location_city": null,
        "location_state": null,
        "location_country": "United States",
        "achievement_count": 0,
        "kudos_count": 1,
        "comment_count": 0,
        "athlete_count": 1,
        "photo_count": 0,
        "map": {
            "id": "a12631351782",
            "summary_polyline": "",
            "resource_state": 2
        },
        "trainer": true,
        "commute": false,
        "manual": false,
        "private": false,
        "visibility": "everyone",
        "flagged": false,
        "gear_id": null,
        "start_latlng": [],
        "end_latlng": [],
        "average_speed": 0,
        "max_speed": 0,
        "has_heartrate": true,
        "average_heartrate": 94.1,
        "max_heartrate": 141,
        "heartrate_opt_out": false,
        "display_hide_heartrate_option": true,
        "elev_high": 0,
        "elev_low": 0,
        "upload_id": 13466930144,
        "upload_id_str": "13466930144",
        "external_id": "E262A789-A536-457D-A4E0-E05156826DD3.fit",
        "from_accepted_tag": false,
        "pr_count": 0,
        "total_photo_count": 0,
        "has_kudoed": false
    },
    {
        "resource_state": 2,
        "athlete": {
            "id": 145570628,
            "resource_state": 1
        },
        "name": "Afternoon Run",
        "distance": 5011.3,
        "moving_time": 1736,
        "elapsed_time": 1740,
        "total_elevation_gain": 38.8,
        "type": "Run",
        "sport_type": "Run",
        "workout_type": null,
        "id": 12625685705,
        "start_date": "2024-10-11T00:01:09Z",
        "start_date_local": "2024-10-10T17:01:09Z",
        "timezone": "(GMT-08:00) America/Los_Angeles",
        "utc_offset": -25200,
        "location_city": null,
        "location_state": null,
        "location_country": "United States",
        "achievement_count": 4,
        "kudos_count": 1,
        "comment_count": 0,
        "athlete_count": 1,
        "photo_count": 0,
        "map": {
            "id": "a12625685705",
            "summary_polyline": "sndmEtwsnUm@Cs@y@YSOGyBBWGYQMCS@q@NIBEN@j@LVFPAtADTHLLHPBdB@bARTJBHBRAnA@lACbBDpBDTFJNJRFbDCTCjACJCLKD}EC{BDgBE_BGUGOUUICeA@_@BcAA[CIGOYi@i@WIcCEQEQIMAkANEBGN@h@LTDN@hBN^RJJ?n@GZ?~@Fd@LJHDJBRATAjGFzABLFJb@LhBB`@Cb@DPE^?REXAHCDQBgBEwABk@@cEEkBIWGIYSWEqDEKIIS_@c@SOMCgA@u@EUEYMS?m@JSHKJALAN@NPTLt@El@?Z@DJNLHV@v@C`A@n@RPNDZAbB@`EA~@?NLVLJNDtBDlCCZAJE?cDCeCBi@AgC@_AA]K[UQWG_BB{AEu@cASOQEUBaBCYEYOIAQ@[H[@KBGPBh@P\\DTBf@Cv@@NJPLFHB`AGv@Dr@LNDJH",
            "resource_state": 2
        },
        "trainer": false,
        "commute": false,
        "manual": false,
        "private": false,
        "visibility": "everyone",
        "flagged": false,
        "gear_id": null,
        "start_latlng": [
            33.77817467786372,
            -117.91008959524333
        ],
        "end_latlng": [
            33.777971919626,
            -117.91015958413482
        ],
        "average_speed": 2.887,
        "max_speed": 4.888,
        "has_heartrate": true,
        "average_heartrate": 172.7,
        "max_heartrate": 186,
        "heartrate_opt_out": false,
        "display_hide_heartrate_option": true,
        "elev_high": 35.6,
        "elev_low": 13,
        "upload_id": 13460800958,
        "upload_id_str": "13460800958",
        "external_id": "5602A64D-9D34-4A0D-A2BA-DB9A13D5FF48.fit",
        "from_accepted_tag": false,
        "pr_count": 2,
        "total_photo_count": 0,
        "has_kudoed": false
    },
    {
        "resource_state": 2,
        "athlete": {
            "id": 145570628,
            "resource_state": 1
        },
        "name": "Morning Weight Training",
        "distance": 0,
        "moving_time": 7768,
        "elapsed_time": 7768,
        "total_elevation_gain": 0,
        "type": "WeightTraining",
        "sport_type": "WeightTraining",
        "id": 12624331567,
        "start_date": "2024-10-10T17:42:12Z",
        "start_date_local": "2024-10-10T10:42:12Z",
        "timezone": "(GMT-07:00) America/Creston",
        "utc_offset": -25200,
        "location_city": null,
        "location_state": null,
        "location_country": "United States",
        "achievement_count": 0,
        "kudos_count": 1,
        "comment_count": 0,
        "athlete_count": 1,
        "photo_count": 0,
        "map": {
            "id": "a12624331567",
            "summary_polyline": "",
            "resource_state": 2
        },
        "trainer": true,
        "commute": false,
        "manual": false,
        "private": false,
        "visibility": "everyone",
        "flagged": false,
        "gear_id": null,
        "start_latlng": [],
        "end_latlng": [],
        "average_speed": 0,
        "max_speed": 0,
        "has_heartrate": true,
        "average_heartrate": 133.5,
        "max_heartrate": 174,
        "heartrate_opt_out": false,
        "display_hide_heartrate_option": true,
        "elev_high": 0,
        "elev_low": 0,
        "upload_id": 13459362483,
        "upload_id_str": "13459362483",
        "external_id": "B9F3A73F-9B18-42A2-80B3-C4EF368A7753.fit",
        "from_accepted_tag": false,
        "pr_count": 0,
        "total_photo_count": 0,
        "has_kudoed": false
    },
    {
        "resource_state": 2,
        "athlete": {
            "id": 145570628,
            "resource_state": 1
        },
        "name": "Morning Stair-Stepper",
        "distance": 0,
        "moving_time": 1141,
        "elapsed_time": 1141,
        "total_elevation_gain": 0,
        "type": "StairStepper",
        "sport_type": "StairStepper",
        "id": 12606339061,
        "start_date": "2024-10-08T15:16:40Z",
        "start_date_local": "2024-10-08T08:16:40Z",
        "timezone": "(GMT-07:00) America/Creston",
        "utc_offset": -25200,
        "location_city": null,
        "location_state": null,
        "location_country": "United States",
        "achievement_count": 0,
        "kudos_count": 1,
        "comment_count": 0,
        "athlete_count": 1,
        "photo_count": 0,
        "map": {
            "id": "a12606339061",
            "summary_polyline": "",
            "resource_state": 2
        },
        "trainer": true,
        "commute": false,
        "manual": false,
        "private": false,
        "visibility": "everyone",
        "flagged": false,
        "gear_id": null,
        "start_latlng": [],
        "end_latlng": [],
        "average_speed": 0,
        "max_speed": 0,
        "has_heartrate": true,
        "average_heartrate": 140,
        "max_heartrate": 159,
        "heartrate_opt_out": false,
        "display_hide_heartrate_option": true,
        "elev_high": 0,
        "elev_low": 0,
        "upload_id": 13440201778,
        "upload_id_str": "13440201778",
        "external_id": "16D06F38-48FD-46AE-B7DF-D527125BE6DE.fit",
        "from_accepted_tag": false,
        "pr_count": 0,
        "total_photo_count": 0,
        "has_kudoed": false
    }
]